[wokwi]
version = 1
elf = 'bin/esp3s3_simulation/firmware.elf'
firmware = 'bin/esp3s3_simulation/firmware.bin'

[[chip]]
name = 'soil-sensor'
binary = 'custom-chips-src/custom-chips-bin/soil-sensor-chip.wasm'
